site_name: Technical Indicator Lamp
site_description: S&P 500 지수의 기술적 분석을 자동화하는 도구
site_author: Inyeol Choi
repo_url: https://github.com/ChoiInYeol/technical-indicator-lamp

theme:
  name: material
  language: ko
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true

nav:
  - 홈: index.md
  - 사용자 가이드: user_guide.md
  - API 레퍼런스:
    - technical_indicator: api/technical_indicator.md
    - signal_generator: api/signal_generator.md
    - visualizer: api/visualizer.md
  - 개발자 가이드: developer_guide.md
  - 기여하기:
    - 기여 가이드라인: CONTRIBUTING.md
    - 행동 강령: CODE_OF_CONDUCT.md
  - 변경 이력: CHANGELOG.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ChoiInYeol
      name: GitHub 