name: Daily Analysis

on:
  schedule:
    - cron: '30 21 * * *'  # 매일 UTC 21:30에 실행 (한국 시간 06:30)
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      run: |
        python src/update_spy.py
        python main.py
    
    - name: Commit to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/ output/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily analysis results" && git push)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        destination_dir: assets
        keep_files: true
