name: Daily Analysis

on:
  schedule:
    - cron: '30 21 * * *'  # 매일 UTC 00:00에 실행

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      run: python scripts/run_analysis.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/processed/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update analysis results" && git push)
