name: Daily Analysis

on:
  schedule:
    - cron: '30 21 * * *'  # 매일 UTC 21:30에 실행 (한국 시간 06:30)
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      run: |
        python src/update_spy.py
        python main.py
    
    - name: Copy dashboard to docs
      run: |
        mkdir -p docs/assets
        cp output/dashboard.png docs/assets/
        cp output/dashboard.svg docs/assets/
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/ output/ docs/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily analysis results" && git push)
