name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3
      
    - name: Python 3.11 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mkdocs mkdocs-material pymdown-extensions mkdocstrings[python]
        
    - name: API 문서 생성
      run: |
        mkdir -p docs/api
        for file in $(find src -name "*.py"); do
          filename=$(basename "$file" .py)
          module_path=${file#src/}
          module_path=${module_path//\//.}  # 폴더를 점(.)으로 변환
          module_path=${module_path%.py}    # 확장자 제거
          
          echo "# $module_path" > "docs/api/${filename}.md"
          echo "\`\`\`python" >> "docs/api/${filename}.md"
          cat "$file" >> "docs/api/${filename}.md"
          echo "\`\`\`" >> "docs/api/${filename}.md"
        done
        
    - name: MkDocs 사이트 생성
      run: mkdocs build
      
    - name: GitHub Pages 배포
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./site
        force_orphan: true  # gh-pages 브랜치를 새로 생성

