name: 코드 포맷팅

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install black isort
          
      - name: Black 포맷 검사
        run: black --check src/
        
      - name: isort 검사
        run: isort --check-only src/ 