name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Python 3.11 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 테스트 실행
      run: |
        pytest tests/
        
    - name: CHANGELOG 파싱
      id: changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        version: ${{ github.ref_name }}
        path: ./CHANGELOG.md
        
    - name: GitHub Release 생성
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.changes }}
        files: |
          LICENSE
          README.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 문서 배포
      run: |
        # 여기에 문서 배포 스크립트 추가 (예: GitHub Pages)
        echo "문서 배포 완료" 