name: 보안 검사

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정에 실행

jobs:
  security:
    name: 보안 취약점 검사
    runs-on: ubuntu-latest
    
    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3
      
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety
        
    - name: Bandit 보안 검사
      continue-on-error: true
      run: bandit -r src/ || true
      
    - name: Safety 의존성 검사
      continue-on-error: true
      run: safety check || true
      
    - name: 결과 업로드
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-results
        path: |
          bandit-results.json
          
  dependency-review:
    name: 의존성 리뷰
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3
      
    - name: 의존성 리뷰
      uses: actions/dependency-review-action@v3
